# Exploring how to query and analyze salesforce data using Heroku and Python

## Prerequisites:

- Create a free heroku account (https://www.heroku.com)
- Install a distribution of Python. I would recommend the anaconda distribution (https://www.anaconda.com), which includes Jupyter notebook, a very useful interface for working with Python.
- Need to install either git (https://git-scm.com/) or heroku CLI (https://devcenter.heroku.com/articles/heroku-cli) in order to deploy apps. I already have git installed, so that is what I am going with. Note sure that we will get to that today.
- Note: We may also need to download PostgresSQL on to our local computer... We can find out in the first meeting!

## To create first App

- Log in to Heroku account (https://www.heroku.com)
- Click "Create new app"
- Enter an app name (must be unique across Heroku) and click "Create App".


## Link with Salesforce org

Now your first app is created. We will link the app with a Salesforce org (developer edition for practice) which will allow us to Query our salesforce data directly from Python (or R, or some other interface). First, we need to provision some add-ons.

- In the App, click on the "Overview" tab.
- Click the "Configure Add-ons" link next to "Installed add-ons".
- Under "Add-ons", search for and select "Heroku Postgres". Ensure that plan name states "Hobby Dev - Free" and click "Provision"
- Similarly, search for and select "Heroku Connect", ensuring that the plan name states "Demo Edition - Free" before clicking "Provision".

Now that we have the add-ons, we can link our Heroku App to a Salesforce org.

- Under the "Resources" tab, click on Heroku Connect.
- Under the "Overview" tab, click on "Setup Connection".
- Click on DATABASE_URL (leave schema name as salesforce) and click "Next".
- Select which environment you want to link (Prodiction, Sandbox, etc.) and click "Authorize".
- Enter the log-in information for the Salesforce org that you are linking too.

Now that is Heroku is linked with our Salesforce org, let's select which objects and fields we want to include. For purposes of this excercise, we will link the Opportunity object and the following fields: Name, StageName, IsClosed, IsWon, and Amount.

- While still under Heroku Connect, click the "Mappings" tab and click "Create Mapping".
- Click on the Opportunity object.
- Ensure that the following fields are selected:

        Name
        StageName
        IsClosed
        IsWon
        Amount
        
- Click "Save"

Great! All we need is to record some of the information from our Heroku Postgres add-on in order to query the data from within Python.

- Back under the App dashboard, click "Heroku Postgres".
- Click the "Settings" tab and click "View Credentials".

The information displayed here will be used to access the Postgres database. For the purposes of this example, we need to record URI. Make note of that.

## Using Python to query data from Heroku App

First we need to import three common Python packages: pandas, numpy, and sqlalchemy (specifically, the create_engine definition). If they are not available, run __pip install sqlalchemy__.

The following code imports the required dependancies.

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

The following is a simple function that creates an engine to query our Postgres data from, write a simple query on the Opportunity data, and returns the data. Make sure to change the **data_uri** to the one recorded above.

In [2]:
## Extract Salesforce Opportunity Data.
def Extract_Data():
    data_uri = 'postgres://deudpzonkninai:62ac341b487b680988cd7473ca4a36311e4732257ea13d09f8c50eb79b980aa3@ec2-174-129-203-86.compute-1.amazonaws.com:5432/de28ove754vom1'
    engine = create_engine(data_uri)
    dat = pd.read_sql('''SELECT name, stagename, isclosed, iswon, amount 
                         FROM salesforce.Opportunity
                         WHERE isclosed = True''', engine)
    engine.dispose()
    return dat

dat = Extract_Data()

Now we have the data in Python, and we can do whatever we want!

In [3]:
dat

,name,stagename,isclosed,iswon,amount
0,Edge SLA,Closed Won,True,True,60000.0
1,Grand Hotels SLA,Closed Won,True,True,90000.0
2,Express Logistics Standby Generator,Closed Won,True,True,220000.0
3,University of AZ Portable Generators,Closed Won,True,True,50000.0
4,United Oil Refinery Generators,Closed Won,True,True,915000.0
5,United Oil SLA,Closed Won,True,True,120000.0
6,United Oil Standby Generators,Closed Won,True,True,120000.0
7,GenePoint SLA,Closed Won,True,True,30000.0
8,Grand Hotels Emergency Generators,Closed Won,True,True,210000.0
9,Grand Hotels Generator Installations,Closed Won,True,True,350000.0
10,University of AZ SLA,Closed Won,True,True,90000.0
11,United Oil Emergency Generators,Closed Won,True,True,440000.0
12,United Oil Installations,Closed Won,True,True,270000.0
13,GenePoint Standby Generator,Closed Won,True,True,85000.0
14,Burlington Textiles Weaving Plant Generator,Closed Won,True,True,235000.0
15,United Oil Installations,Closed Won,True,True,235000.0
16,Edge Emergency Generator,Closed Won,True,True,75000.0
17,Edge Installation,Closed Won,True,True,50000.0